version: '3.0'

services:
  grafana:
    container_name: 'lf-datasource'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.5.2}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/lf-datasource
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=lf-datasource
